dns:
    # 基础参数配置

    ip4: false
    # 是否启用ipv4

    ip6: true
    #是否启用ipv6

    ttl: 200
    priority: 5

account:
    #域名服务器参数配置
    hostker:
        email: jianghhui@gmail.com
        token: 8caf0a0767194091204c5eb721465aaefc1acb7c913aaa1e414db052851855cc
        id: 202798
    aliyun:
